version: "3.3"

services:
  mysqlcon:
    image: mysql:latest
    #container_name: mysqlcon
    environment:
      - MYSQL_ROOT_PASSWORD=redhat
      - MYSQL_DATABASE=db_name
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
    volumes:
      - /blogdb:/var/lib/mysql
    # Set the initial scale for mysqlcon to 1 replica
    deploy:
      replicas: 2

  wpcon:
    image: wordpress:latest
    environment:
      - WORDPRESS_DB_HOST=mysqlcon
      - WORDPRESS_DB_USER=db_user
      - WORDPRESS_DB_PASSWORD=db_password
      - WORDPRESS_DB_NAME=db_name
    ports:
      - "8780-8783:80"
    links:
            - mysqlcon
    # Set the initial scale for wpcon to 3 replicas
    deploy:
      replicas: 4
